apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-eks-deployment
  labels:
    app: node-eks
spec:
  replicas: 3
  selector:
    matchLabels:
      app: node-eks
  template:
    metadata:
      labels:
        app: node-eks
    spec:
      containers:
      - name: node-eks
        image: 542685624457.dkr.ecr.ap-south-1.amazonaws.com/goapp:v4
        ports:
        - containerPort: 8080