apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeeks
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: nodeeks
  template:
    metadata:
      labels:
        app: nodeeks
    spec:
      containers:
        - name: nodeeks
          image: 651010102653.dkr.ecr.ap-southeast-1.amazonaws.com/nodeeks:latest
          ports:
            - containerPort: 8000
          env:
            - name: PORT
              value: "8000"
---
apiVersion: v1
kind: Service
metadata:
  name: nodeeks
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8000
  selector:
    app: nodeeks