apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeeks
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodeeks
  template:
    metadata:
      labels:
        app: nodeeks
    spec:
      containers:
        - name: nodeeks
          image: 651010102653.dkr.ecr.ap-southeast-1.amazonaws.com/nodeeks:latest
          imagePullPolicy: Always
          resources:
            limits:
              memory: 512Mi
              cpu: "1"
            requests:
              memory: 256Mi
              cpu: "1"
          ports:
            - containerPort: 8000