apiVersion: v1
kind: Service
metadata:
  labels:
    app: nodeeks
    name: nodeeks
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8000
  type: LoadBalancer
  selector:
    app: nodeeks