apiVersion: v1
kind: Service
metadata:
  labels:
    name: node-eks
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  type: LoadBalancer
  selector:
    app: node-eks